# Generated by Django 3.2.8 on 2021-10-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notesdb',
            fields=[
                ('notesNo', models.IntegerField(primary_key=True, serialize=False)),
                ('notesdata', models.CharField(max_length=500)),
                ('notesName', models.CharField(max_length=30)),
            ],
        ),
    ]
